name: MoonAuSosiGi's Lab
title: MoonAuSosiGi's Lab
description: 프로젝트 정리용 블로그
tags:
  - blog
  - gamedev
  - programmer
  - game programmer
email: moonausosigi@gmail.com
disqus_username:
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact

